### ISSUE TITLE
error bulid

### ISSUE THREAD

**Issue by Ahmed5574** [xanaxas/Tree-Visualizer#1]
Error	1	Invalid expression term 'int'	F:\Tree-Visualizer-main\Tree-Visualizer-main\TreeVisualizer\TreeVisualizer\MainWindow.cs	70	56	TreeVisualizer
Error	2	Invalid expression term ')'	F:\Tree-Visualizer-main\Tree-Visualizer-main\TreeVisualizer\TreeVisualizer\MainWindow.cs	70	61	TreeVisualizer
Error	3	; expected	F:\Tree-Visualizer-main\Tree-Visualizer-main\TreeVisualizer\TreeVisualizer\MainWindow.cs	70	61	TreeVisualizer
Error	4	Invalid expression term ')'	F:\Tree-Visualizer-main\Tree-Visualizer-main\TreeVisualizer\TreeVisualizer\MainWindow.cs	70	62	TreeVisualizer
Error	5	; expected	F:\Tree-Visualizer-main\Tree-Visualizer-main\TreeVisualizer\TreeVisualizer\MainWindow.cs	70	62	TreeVisualizer
Error	6	; expected	F:\Tree-Visualizer-main\Tree-Visualizer-main\TreeVisualizer\TreeVisualizer\MainWindow.cs	70	63	TreeVisualizer
Error	7	Invalid expression term '.'	F:\Tree-Visualizer-main\Tree-Visualizer-main\TreeVisualizer\TreeVisualizer\DrawBox.cs	43	106	TreeVisualizer
Error	8	Syntax error, ':' expected	F:\Tree-Visualizer-main\Tree-Visualizer-main\TreeVisualizer\TreeVisualizer\DrawBox.cs	43	107	TreeVisualizer
Error	9	Syntax error, '(' expected	F:\Tree-Visualizer-main\Tree-Visualizer-main\TreeVisualizer\TreeVisualizer\DrawBox.cs	43	128	TreeVisualizer
Error	10	The best overloaded method match for 'int.TryParse(string, out int)' has some invalid arguments	F:\Tree-Visualizer-main\Tree-Visualizer-main\TreeVisualizer\TreeVisualizer\MainWindow.cs	45	18	TreeVisualizer
Error	11	Argument 2: cannot convert from 'out intvalue' to 'out int'	F:\Tree-Visualizer-main\Tree-Visualizer-main\TreeVisualizer\TreeVisualizer\MainWindow.cs	45	52	TreeVisualizer
Error	12	The name 'intvalue' does not exist in the current context	F:\Tree-Visualizer-main\Tree-Visualizer-main\TreeVisualizer\TreeVisualizer\MainWindow.cs	45	52	TreeVisualizer
Error	13	The name 'value' does not exist in the current context	F:\Tree-Visualizer-main\Tree-Visualizer-main\TreeVisualizer\TreeVisualizer\MainWindow.cs	53	41	TreeVisualizer
Error	14	The name 'value' does not exist in the current context	F:\Tree-Visualizer-main\Tree-Visualizer-main\TreeVisualizer\TreeVisualizer\MainWindow.cs	58	33	TreeVisualizer

**Comment by pasimetes** [comment]
Must be a problem with your environment.
